# Server
server:
  port: 8082

#Gmail SMTP Server
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: perion1014
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

# Mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: "true"

# File I/O
file:
  dir: shopping-mall/src/main/resources/static/images/itemImages/

# Dev
spring:
  thymeleaf:
    cache: "false"
  freemarker:
    cache: "false"
  devtools:
    livereload:
      enabled: "true"
  servlet:
    multipart:
      enabled: "true"
      max-file-size: "10MB"
      max-request-size: "40MB"

  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/perion?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    password: "1234!@#$"